version: '3.3'
services:
  coin:
    image: dockerqiqi/coin:v1
    restart: always
    build:
      context: docker
      dockerfile: Dockerfile
    env_file:
      - .env
  influxdb:
     image: influxdb
     container_name: influxdb
     ports:
      - 8086:8086
     volumes:
      - /var/lib/influxdb:/var/lib/influxdb
     env_file:
      - .env
     environment:
      
   redis:
     image: redis:6.0.9  # 确保使用具体的镜像版本
     ports:
      - "6379:6379"
        #volumes:
        #- redis_data:/data