version: '3.3'
services:
  coin:
    image: dockerqiqi/coin:v1
    restart: always
    build:
      context: docker
      dockerfile: Dockerfile
    env_file:
      - .env
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - /var/lib/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_TOKEN=testruiqi
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379